Use the new api_config in all services
kernelci/kernelci-pipeline pull request #199
Opened 2023-01-31 13:12 UTC by gctucker

Replace the now-deprecated db_config with the new api_config which is pending to be merged in kernelci-core with https://github.com/kernelci/kernelci-core/pull/1650

Update all the services accordingly.  This is to start transitioning away from the old Database abstraction layer class in kernelci-core into supporting only the KernelCI API.

2023-02-13 10:57 UTC, gctucker commented
Tested OK on staging with `kver`:
```
02/10/2023 05:35:10 PM UTC [INFO] Listening for available checkout events
02/10/2023 05:35:10 PM UTC [INFO] Press Ctrl-C to stop.
Getting kernel source tree...
Source directory: /tmp/kci/linux-kernelci-staging-mainline-staging-mainline-20230210.8
Running job...
Checking kernel revision
Result: pass
02/13/2023 09:50:56 AM UTC [INFO] Listening for available checkout events
02/13/2023 09:50:56 AM UTC [INFO] Press Ctrl-C to stop.
Getting kernel source tree...
Source directory: /tmp/kci/linux-kernelci-staging-mainline-staging-mainline-20230213.0
Running job...
Checking kernel revision
Result: pass
Getting kernel source tree...
Source directory: /tmp/kci/linux-kernelci-staging-next-staging-next-20230212.0
Running job...
Checking kernel revision
Result: pass
Getting kernel source tree...
Source directory: /tmp/kci/linux-kernelci-staging-stable-staging-stable-20230213.0
Running job...
Checking kernel revision
Result: fail
Getting kernel source tree...
Source directory: /tmp/kci/linux-mainline-master-v6.2-rc8
Running job...
Checking kernel revision
Result: pass
```
It looks like the k8s runner is not working as expected so there's no KUnit results, but that's probably a different kind of issues.

2023-02-16 05:13 UTC, JenySadadia requested changes
As per the latest changes, please update `pending_states` in `timeout`:
```
self._pending_states = [
            state.value for state in self._api.node_states
            if state != state.DONE
        ]

```

2023-02-16 07:12 UTC, gctucker commented
> As per the latest changes, please update `pending_states` in `timeout`:
> 
> ```
> self._pending_states = [
>             state.value for state in self._api.node_states
>             if state != state.DONE
>         ]
> ```

OK I'll do that as a follow-up PR.

2023-02-16 10:31 UTC, gctucker commented
Ah sorry I see, it's about changing `self._db` to `self._api`.  I'm rebasing and sending an update now.

2023-02-16 10:32 UTC, gctucker commented
OK fixed this now.  I see the error in the logs:
```
AttributeError: 'Timeout' object has no attribute '_db'
```

2023-02-17 09:09 UTC, gctucker commented
Tested OK on staging:
```
[INFO] Listening for events... 
[INFO] Press Ctrl-C to stop.
[INFO] Time                        Commit        Node Id                   State      Result    Name
[INFO] 2023-02-17 08:08:13.426516  198538cb7232  63ef35ed5a3ec83513e79d9c  Running    -         checkout
[INFO] 2023-02-17 08:09:17.364122  ffda28d272fe  63ef35ec5a3ec83513e79d9b  Available  -         checkout
[INFO] 2023-02-17 08:09:17.525189  ffda28d272fe  63ef362d5a3ec83513e79d9d  Running    -         kver
[INFO] 2023-02-17 08:09:17.533777  ffda28d272fe  63ef362d5a3ec83513e79d9e  Running    -         kunit
[INFO] 2023-02-17 08:09:50.183437  ffda28d272fe  63ef362d5a3ec83513e79d9d  Done       Pass      kver
[INFO] 2023-02-17 08:10:49.937380  198538cb7232  63ef35ed5a3ec83513e79d9c  Available  -         checkout
[INFO] 2023-02-17 08:10:50.068060  198538cb7232  63ef368a5a3ec83513e79d9f  Running    -         kver
[INFO] 2023-02-17 08:10:50.096564  198538cb7232  63ef368a5a3ec83513e79da0  Running    -         kunit
[INFO] 2023-02-17 08:11:13.799797  198538cb7232  63ef368a5a3ec83513e79d9f  Done       Pass      kver
[INFO] 2023-02-17 08:20:13.890994  ffda28d272fe  63ef35ec5a3ec83513e79d9b  Closing    -         checkout
[INFO] 2023-02-17 08:21:14.660325  198538cb7232  63ef35ed5a3ec83513e79d9c  Closing    -         checkout
```
The timeout service didn't crash so it's all looking fine now.

2023-02-17 09:10 UTC, gctucker commented
@JenySadadia Please take another look, I believe this is all ready to be merged now.

2023-02-17 11:03 UTC, JenySadadia commented on src/runner.py
> +        self._api_config_yaml = yaml.dump(self._api_config)
I would like to know why this has changed to not use `to_yaml`.

2023-02-17 11:26 UTC, JenySadadia commented on src/runner.py
> +        self._api_config_yaml = yaml.dump(self._api_config)
OK

2023-02-17 11:26 UTC, JenySadadia approved these changes

2023-02-17 11:27 UTC, merged