Update Node.status in client scripts
kernelci/kernelci-pipeline pull request #27
Opened 2022-02-28 05:42 UTC by JenySadadia

Node.status is now defined as Enum type, with 'pending'
as its default value. Hence, modified condition to
check status in client scripts.

Signed-off-by: Jeny Sadadia <jeny.sadadia@gmail.com>

2022-03-01 14:26 UTC, gctucker requested changes
The `tarball.py` script is not setting a correct status value:
https://staging.kernelci.org:9088/container/2f837bd7bb63
```
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://staging.kernelci.org:9000/node/621e2ab9d45fcf006e8c954a
```

2022-03-01 15:28 UTC, JenySadadia commented
> 

A change was required when calling `_update_node` function.
I have updated the PR. Could you please test again? @gctucker

2022-03-03 08:53 UTC, gctucker approved these changes
Tested OK on staging:
```
today at 8:05:15 AMListening for events... 
today at 8:05:15 AMPress Ctrl-C to stop.
today at 8:05:15 AMTime                        Commit        Status    Name
today at 8:05:15 AM2022-03-03 08:05:15.887487  a7ec3a290b9d  Pending   checkout
today at 8:06:16 AM2022-03-03 08:06:16.647050  a7ec3a290b9d  Pass      checkout
today at 8:06:16 AM2022-03-03 08:06:16.773701  a7ec3a290b9d  Pending   check-describe
today at 8:06:52 AM2022-03-03 08:06:52.660823  a7ec3a290b9d  Fail      check-describe
```
https://staging.kernelci.org:9088/container/39734e7191ad
(check-describe is failing but that's expected)

Also with KCIDB:
https://kcidb.kernelci.org/d/revision/revision?orgId=1&var-git_commit_hash=a7ec3a290b9d79f472e39a303431c4661c769abd&var-patchset_hash=&var-dataset=playground_kcidb_01&var-origin=All&var-build_architecture=All&var-build_config_name=All&var-test_path=

2022-03-03 08:54 UTC, gctucker reviewed
One thing though, commit titles with "modify something" don't really explain what the change is doing. Something like "convert to enum" would be better. But I think we can merge this now, it's more something to keep in mind for the future.

2022-03-03 08:54 UTC, merged

2022-03-03 09:12 UTC, JenySadadia commented
> One thing though, commit titles with "modify something" don't really explain what the change is doing. Something like "convert to enum" would be better. But I think we can merge this now, it's more something to keep in mind for the future.

Okay. Thanks.