kbuild.jinja2: Add dtbs_check parameter
kernelci/kernelci-pipeline pull request #454
Opened 2024-03-04 08:37 UTC by nuclearcat

Add dtbs_check as parameter for kbuild

2024-03-05 15:35 UTC, a-wai requested changes

2024-03-05 15:35 UTC, a-wai commented on config/pipeline.yaml
> +      defconfig: defconfig
```suggestion
      <<: *kbuild-gcc-10-arm64-params
```

2024-03-05 15:35 UTC, a-wai commented on config/pipeline.yaml
> +      branch: 'master'
Those should go into the job definition, not the scheduler entry (this could be a future TODO though).

2024-03-05 16:09 UTC, a-wai commented on config/pipeline.yaml
> +    params:
```suggestion
    kind: test
    params:
```
`kbuild-gcc-10-arm64-job` has `kind: kbuild`, I think this one should be different

2024-03-05 16:27 UTC, a-wai commented on config/pipeline.yaml
> +    params:
yes, that's what I meant, and also why we keep using the kbuild template; but the node/results should clearly be identified as `test` for easier understanding.

2024-03-06 08:57 UTC, nuclearcat commented
Thanks all, merging

2024-03-06 08:58 UTC, merged