config/scripts: align check-describe template with kubernetes
kernelci/kernelci-pipeline pull request #61
Opened 2022-05-18 13:34 UTC by gctucker

Align the scripts/check-describe.jinja2 template with the one in
kubernetes as an intermediate step to merge them together.  The only
difference left is the name of the base template.

Signed-off-by: Guillaume Tucker <guillaume.tucker@collabora.com>

2022-05-18 19:49 UTC, gctucker commented
Tested OK locally with both shell and k8s:
```
$ DOT_ENV=env-staging docker-compose run runner /bin/bash
kernelci@f4b1c0ad7236:~$ ./pipeline/runner.py --settings=config/kernelci-staging.conf run --db-config=staging.kernelci.org --git-commit=3bda6aad596de31ddad90cbf5d7e70dcadafac9c --lab-config=k8s-gke-eu-west4 --plan=check-describe --target=kubernetes_python
05/18/2022 07:44:05 PM UTC [INFO] Tarball: http://staging.kernelci.org:9080/linux-kernelci-staging-mainline-staging-mainline-20220410.0.tar.gz
05/18/2022 07:44:05 PM UTC [INFO] Creating test node
05/18/2022 07:44:05 PM UTC [INFO] Generating job
05/18/2022 07:44:05 PM UTC [INFO] tmp: /home/kernelci/output/tmptmexjhgu
05/18/2022 07:44:06 PM UTC [INFO] output_file: /home/kernelci/output/tmptmexjhgu/kci-62854c85f2e90a569a7ea8e0-check-describe-jw5xqzvn.yaml
05/18/2022 07:44:06 PM UTC [INFO] Running test
kernelci@f4b1c0ad7236:~$ ./pipeline/runner.py --settings=config/kernelci-staging.conf run --db-config=staging.kernelci.org --git-commit=3bda6aad596de31ddad90cbf5d7e70dcadafac9c --lab-config=shell --plan=check-describe --target=shell_python05/18/2022 07:45:26 PM UTC [INFO] Tarball: http://staging.kernelci.org:9080/linux-kernelci-staging-mainline-staging-mainline-20220410.0.tar.gz
05/18/2022 07:45:26 PM UTC [INFO] Creating test node
05/18/2022 07:45:26 PM UTC [INFO] Generating job
05/18/2022 07:45:26 PM UTC [INFO] tmp: /home/kernelci/output/tmpep40i_p4
05/18/2022 07:45:26 PM UTC [INFO] output_file: /home/kernelci/output/tmpep40i_p4/check-describe
05/18/2022 07:45:26 PM UTC [INFO] Running test
05/18/2022 07:45:26 PM UTC [INFO] Waiting...
Getting kernel source tree
Checking git describe
Result: FAIL
05/18/2022 07:45:51 PM UTC [INFO] ...done
```

2022-05-23 10:56 UTC, JenySadadia commented
@gctucker  Why do we need to remove space using  `{%- block}`?

2022-05-23 11:20 UTC, gctucker commented
> 

Simply to avoid having loads of empty lines in the generated YAML or Python.

2022-06-13 07:03 UTC, JenySadadia commented
Tested on local. Runner exists.

```
kernelci-pipeline-tarball | 06/13/2022 07:00:59 AM UTC [INFO] Tarball created
kernelci-pipeline-tarball | 06/13/2022 07:00:59 AM UTC [INFO] Uploading /home/kernelci/data/output/linux-mainline-master-v5.19-rc2.tar.gz
kernelci-pipeline-tarball | Warning: Permanently added '[172.17.0.1]:8022' (ECDSA) to the list of known hosts.
kernelci-pipeline-tarball | 06/13/2022 07:00:59 AM UTC [INFO] Upload complete
kernelci-pipeline-runner | 06/13/2022 07:00:59 AM UTC [INFO] Tarball: http://172.17.0.1:8002/linux-mainline-master-v5.19-rc2.tar.gz
kernelci-pipeline-runner | 06/13/2022 07:00:59 AM UTC [INFO] Creating test node
kernelci-pipeline-notifier | 06/13/2022 07:00:59 AM UTC [INFO] 2022-06-13 07:00:59.886734  b13baccc3850  Pass      checkout
kernelci-pipeline-runner | 06/13/2022 07:00:59 AM UTC [INFO] Generating job
kernelci-pipeline-runner | 06/13/2022 07:00:59 AM UTC [INFO] tmp: /home/kernelci/output/tmp3s1io1ts
kernelci-pipeline-test_report | 06/13/2022 07:00:59 AM UTC [INFO] mainline/master v5.19-rc2: 1 runs, 0 failures
kernelci-pipeline-test_report | 
kernelci-pipeline-test_report | test            | result
kernelci-pipeline-test_report | ----------------+-------
kernelci-pipeline-test_report | checkout        | pass
kernelci-pipeline-test_report | 
kernelci-pipeline-test_report |   Tree:     mainline
kernelci-pipeline-test_report |   Branch:   master
kernelci-pipeline-test_report |   Describe: v5.19-rc2
kernelci-pipeline-test_report |   URL:      https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
kernelci-pipeline-test_report |   SHA1:     b13baccc3850ca8b8cccbf8ed9912dbaa0fdf7f3
kernelci-pipeline-notifier | 06/13/2022 07:00:59 AM UTC [INFO] 2022-06-13 07:00:59.898705  b13baccc3850  Pending   check-describe
kernelci-pipeline-runner exited with code 0

```

2022-06-13 07:09 UTC, JenySadadia requested changes
Need to fix the `base-python.jinja2` template not found issue.

After manually copying templates to config/scripts, it is working.
```
ernelci-pipeline-runner | 06/13/2022 07:05:17 AM UTC [INFO] output_file: /home/kernelci/output/tmpo2r33qly/check-describe
kernelci-pipeline-runner | 06/13/2022 07:05:17 AM UTC [INFO] Running test
kernelci-pipeline-runner | Getting kernel source tree
kernelci-pipeline-runner | Checking git describe
kernelci-pipeline-runner | Result: PASS
kernelci-pipeline-notifier | 06/13/2022 07:05:27 AM UTC [INFO] 2022-06-13 07:05:27.191128  b13baccc3850  Pass      check-describe
kernelci-pipeline-test_report | 06/13/2022 07:05:27 AM UTC [INFO] mainline/master v5.19-rc2: 1 runs, 0 failures
kernelci-pipeline-test_report | 
kernelci-pipeline-test_report | test            | result
kernelci-pipeline-test_report | ----------------+-------
kernelci-pipeline-test_report | check-describe  | pass
kernelci-pipeline-test_report | 
kernelci-pipeline-test_report |   Tree:     mainline
kernelci-pipeline-test_report |   Branch:   master
kernelci-pipeline-test_report |   Describe: v5.19-rc2
kernelci-pipeline-test_report |   URL:      https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
kernelci-pipeline-test_report |   SHA1:     b13baccc3850ca8b8cccbf8ed9912dbaa0fdf7f3

```

2022-06-20 20:58 UTC, gctucker commented
@JenySadadia The `base-python.jinja2` template is coming from `kernelci-core`, so I don't understand what you think should be fixed in this PR.

2022-06-22 07:06 UTC, JenySadadia commented
> @JenySadadia The `base-python.jinja2` template is coming from `kernelci-core`, so I don't understand what you think should be fixed in this PR.

`kernelci-core` failed to find the template. That should be fixed before merging this one.

2022-06-22 07:54 UTC, gctucker commented
OK I'll go through this again to double check

2022-06-28 07:08 UTC, JenySadadia commented
Tested OK with `lab_config: shell`:

```
kernelci-pipeline-notifier | 06/28/2022 07:00:36 AM UTC [INFO] 2022-06-28 07:00:36.010483  941e3e791269  Pending   check-describe
kernelci-pipeline-runner | 06/28/2022 07:00:36 AM UTC [INFO] output_file: /home/kernelci/output/tmpxk1yf3nt/check-describe
kernelci-pipeline-runner | 06/28/2022 07:00:36 AM UTC [INFO] Running test
kernelci-pipeline-runner | Getting kernel source tree
kernelci-pipeline-runner | Checking git describe
kernelci-pipeline-runner | Result: PASS
kernelci-pipeline-notifier | 06/28/2022 07:00:45 AM UTC [INFO] 2022-06-28 07:00:45.679167  941e3e791269  Pass      check-describe
kernelci-pipeline-test_report | 06/28/2022 07:00:45 AM UTC [INFO] mainline/master v5.19-rc4-14-g941e3e791269: 1 runs, 0 failures
kernelci-pipeline-test_report | 
kernelci-pipeline-test_report | test            | result
kernelci-pipeline-test_report | ----------------+-------
kernelci-pipeline-test_report | check-describe  | pass
kernelci-pipeline-test_report | 
kernelci-pipeline-test_report |   Tree:     mainline
kernelci-pipeline-test_report |   Branch:   master
kernelci-pipeline-test_report |   Describe: v5.19-rc4-14-g941e3e791269
kernelci-pipeline-test_report |   URL:      https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
kernelci-pipeline-test_report |   SHA1:     941e3e7912696b9fbe3586083a7c2e102cee7a87
```

2022-06-28 07:09 UTC, JenySadadia commented
With `lab_config: k8s-gke-eu-west4`:
```
kernelci-pipeline-notifier | 06/28/2022 07:05:27 AM UTC [INFO] 2022-06-28 07:05:27.702531  941e3e791269  Pending   check-describe
kernelci-pipeline-test_report | 06/28/2022 07:05:27 AM UTC [INFO] mainline/master v5.19-rc4-14-g941e3e791269: 1 runs, 0 failures
kernelci-pipeline-test_report | 
kernelci-pipeline-test_report | test            | result
kernelci-pipeline-test_report | ----------------+-------
kernelci-pipeline-test_report | checkout        | pass
kernelci-pipeline-test_report | 
kernelci-pipeline-test_report |   Tree:     mainline
kernelci-pipeline-test_report |   Branch:   master
kernelci-pipeline-test_report |   Describe: v5.19-rc4-14-g941e3e791269
kernelci-pipeline-test_report |   URL:      https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
kernelci-pipeline-test_report |   SHA1:     941e3e7912696b9fbe3586083a7c2e102cee7a87
kernelci-pipeline-runner | 06/28/2022 07:05:27 AM UTC [INFO] output_file: /home/kernelci/output/tmpt4zhu9dn/kci-62baa837c0ce9131b1569bf6-check-describe-175jqihe.yaml
kernelci-pipeline-runner | 06/28/2022 07:05:27 AM UTC [INFO] Running test
kernelci-pipeline-runner exited with code 0
```

Do I need any other settings for this? @gctucker

2022-06-28 20:02 UTC, gctucker commented
> With `lab_config: k8s-gke-eu-west4`:
> 
> ```
> kernelci-pipeline-notifier | 06/28/2022 07:05:27 AM UTC [INFO] 2022-06-28 07:05:27.702531  941e3e791269  Pending   check-describe
> kernelci-pipeline-test_report | 06/28/2022 07:05:27 AM UTC [INFO] mainline/master v5.19-rc4-14-g941e3e791269: 1 runs, 0 failures
> kernelci-pipeline-test_report | 
> kernelci-pipeline-test_report | test            | result
> kernelci-pipeline-test_report | ----------------+-------
> kernelci-pipeline-test_report | checkout        | pass
> kernelci-pipeline-test_report | 
> kernelci-pipeline-test_report |   Tree:     mainline
> kernelci-pipeline-test_report |   Branch:   master
> kernelci-pipeline-test_report |   Describe: v5.19-rc4-14-g941e3e791269
> kernelci-pipeline-test_report |   URL:      https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
> kernelci-pipeline-test_report |   SHA1:     941e3e7912696b9fbe3586083a7c2e102cee7a87
> kernelci-pipeline-runner | 06/28/2022 07:05:27 AM UTC [INFO] output_file: /home/kernelci/output/tmpt4zhu9dn/kci-62baa837c0ce9131b1569bf6-check-describe-175jqihe.yaml
> kernelci-pipeline-runner | 06/28/2022 07:05:27 AM UTC [INFO] Running test
> kernelci-pipeline-runner exited with code 0
> ```
> 
> Do I need any other settings for this? @gctucker

I think that's great, thank you. I guess you might not have the Kubernetes credentials installed locally, so the job wasn't submitted. At least it seems like it was generated correctly so that's all good.

If you're happy with this PR then please "approve" it in the review to confirm, and feel free to merge it too as I believe you have permissions to do that. Or let me know if there's anything you're still not sure about.

2022-06-29 05:49 UTC, JenySadadia approved these changes
LGTM :)

2022-06-29 05:49 UTC, merged