tast: Fix tree monitoring for Tast tests
kernelci/kernelci-pipeline pull request #939
Opened 2024-12-05 02:03 UTC by denisyuji

As per internal discussion, we will separate the handling of Tast tests in 2 grpous: decoder related Tast tests and other Tast tests.

The Tast decoder related tests will be monitored on the following branches:

- mainline
- collabora-chromeos-kernel
- stable

All other Tast tests will target:

- mainline
- collabora-chromeos-kernel
- stable-rc

2024-12-05 11:29 UTC, laura-nao commented
Thanks @denisyuji - just one note:

> All other Tast tests will target:
> 
>     * mainline
> 
>     * collabora-chromeos-kernel
> 
>     * stable-rc

Non-codec Tast tests were actually configured to run on mainline and stable-rc . The rules were accidentally changed by https://github.com/kernelci/kernelci-pipeline/pull/897 - I suggest updating this PR to fix the rules for non-codec Tast tests (see review comment above).

2024-12-05 11:30 UTC, laura-nao requested changes

2024-12-05 11:30 UTC, laura-nao commented on config/jobs-chromeos.yaml
>          - collabora-chromeos-kernel
Let's revert the configuration for non-codec Tast tests to what it was before https://github.com/kernelci/kernelci-pipeline/pull/897 was merged - so just mainline, and stable-rc.

2024-12-05 18:13 UTC, denisyuji commented
Thank you once again for your review, @laura-nao . That definitely makes sense. I have changed it. Please, see it again

2024-12-06 15:24 UTC, laura-nao approved these changes

2024-12-06 15:25 UTC, laura-nao commented
LGTM now, thanks Denis!

2024-12-06 17:20 UTC, musamaanjum approved these changes
The changes look good! This PR would revert the behvaiour of non-media tast tests to run on mainline and stable-rc.

2024-12-06 18:19 UTC, nuclearcat commented
Thanks all, merging :)

2024-12-06 18:19 UTC, merged