Add h26forge tests in pipeline and scheduler
kernelci/kernelci-pipeline pull request #952
Opened 2024-12-19 09:27 UTC by benjamingaignard

The goal is to run h26forge on platforms with h264 stateless decoders. So far only rk3399 and i.mx8mq got this kind of decoders. Only rk3399 is available in LAVA labs so limit the test to this device.

2024-12-30 22:43 UTC, pawiecz requested changes

2024-12-30 22:43 UTC, pawiecz commented on config/pipeline.yaml
> +    event: *kbuild-gcc-12-arm-node-event
Double-checking: should this be triggered by an `arm` not `arm64` event?

2024-12-30 22:43 UTC, pawiecz commented on config/jobs-chromeos.yaml
> +    template: 'h26forge-debian.jinja2'
I was unable to locate this template in [config/runtime](https://github.com/kernelci/kernelci-pipeline/tree/main/config/runtime).

Will there be [a lot of setup](https://github.com/kernelci/kernelci-pipeline/blob/main/config/runtime/fluster-chromeos.jinja2) in the new template? Maybe `generic.jinja2` will be sufficient?

2024-12-30 22:43 UTC, pawiecz commented on config/jobs-chromeos.yaml
> +      nfsroot: 'https://storage.staging.kernelci.org/rootfs/bookworm-gst-h26forge/20241218.0/{debarch}/'
I'm afraid these might no longer be available.

I'll trigger a rebuild before verifying this PR in the lab.

2025-01-02 08:50 UTC, benjamingaignard commented on config/jobs-chromeos.yaml
> +      nfsroot: 'https://storage.staging.kernelci.org/rootfs/bookworm-gst-h26forge/20241218.0/{debarch}/'
I have done a PR to create a rootfs with all the needed tools:
https://github.com/kernelci/kernelci-core/pull/2759

It include build GStreamer and h26forge

2025-01-02 08:52 UTC, benjamingaignard commented on config/jobs-chromeos.yaml
> +    template: 'h26forge-debian.jinja2'
h26forge is written in rust and require rustc compiler.
To perform the tests it use GStreamer to play the h264 bitstreams generated by h26forge.
I have create a rootfs for this: https://github.com/kernelci/kernelci-core/pull/2759

2025-01-02 08:52 UTC, benjamingaignard commented on config/pipeline.yaml
> +    event: *kbuild-gcc-12-arm-node-event
I will change it to use arm64 event.

2025-01-10 08:48 UTC, nuclearcat commented
Tested at staging: https://staging.kernelci.org:9000/viewer?search=parent%3D67801acd7660a65959687036

2025-01-10 08:48 UTC, merged